name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.23", "1.22", "1.21"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false # depends on go.sum
      - run: go mod tidy
      - run: go test -v
      - run: cd gorm && go mod tidy
      - run: go test -v